name: Windows CI

on: [push]

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: "==3.1.*"
          version: "6.5.1"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"
          setup-python: false

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: Package
        run: |
          cd build\out\Release
          windeployqt Aijika.exe --no-translations --no-system-d3d-compiler --no-opengl-sw
          cd ..\..\..
          cp LICENSE.txt build\out\LICENSE.txt
          iscc innosetup.iss

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: Output
